title: Lou Zhou
author: "Lou Zhou"
description: Personal Portfolio of Lou Zhou

theme: minima

base_url: /gh-pages-minima-starter
repository: jsanz/gh-pages-minima-starter

# Minima social links
github_username: Lou-Zhou
linkedin_username: Lou-Zhou

# Minima: show excerpts in the frontpage
show_excerpts: false

minima:
  date_format: "%Y-%m-%d"
  skin: dark

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/blog.md
  - _pages/projects.md
  - _pages/Lou_Zhou_Resume.pdf
include:
    - _pages
    - projects
    - Lou_Zhou_Resume.pdf
exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
